"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ZRegistroTableFooter = exports.ZRegistroTableCell = exports.ZRegistroTableBody = exports.ZRegistroTable = exports.ZPanelElem = exports.ZPaginationPage = exports.ZPaginationBar = exports.ZNavigationTabs = exports.ZNavigationTab = exports.ZModalLogin = exports.ZModal = exports.ZMenuSection = exports.ZMenuDropdown = exports.ZMenu = exports.ZLogo = exports.ZListItem = exports.ZList = exports.ZLink = exports.ZInputMessage = exports.ZInputLabel = exports.ZInput = exports.ZInfoBox = exports.ZIconPackage = exports.ZIcon = exports.ZHeading = exports.ZHeader = exports.ZFooterSocial = exports.ZFooterSection = exports.ZFooterLink = exports.ZFooter = exports.ZDivider = exports.ZCookiebar = exports.ZCombobox = exports.ZChip = exports.ZCardList = exports.ZCardIcon = exports.ZCardHeader = exports.ZCardFooter = exports.ZCardCover = exports.ZCardBody = exports.ZCardAlert = exports.ZCard = exports.ZCandybar = exports.ZButtonSort = exports.ZButtonFilter = exports.ZButton = exports.ZBody = exports.ZAppTopbar = exports.ZAppSwitcher = exports.ZAppHeader = void 0;
exports.ZUserDropdown = exports.ZTypography = exports.ZTooltip = exports.ZToggleButton = exports.ZStepperItem = exports.ZStepper = exports.ZSelect = exports.ZRegistroTableStickyFooter = exports.ZRegistroTableRow = exports.ZRegistroTableHeader = exports.ZRegistroTableHead = void 0;
/* eslint-disable */
/* tslint:disable */
/* auto-generated react proxies */
const react_component_lib_1 = require("./react-component-lib");
exports.ZAppHeader = react_component_lib_1.createReactComponent('z-app-header');
exports.ZAppSwitcher = react_component_lib_1.createReactComponent('z-app-switcher');
exports.ZAppTopbar = react_component_lib_1.createReactComponent('z-app-topbar');
exports.ZBody = react_component_lib_1.createReactComponent('z-body');
exports.ZButton = react_component_lib_1.createReactComponent('z-button');
exports.ZButtonFilter = react_component_lib_1.createReactComponent('z-button-filter');
exports.ZButtonSort = react_component_lib_1.createReactComponent('z-button-sort');
exports.ZCandybar = react_component_lib_1.createReactComponent('z-candybar');
exports.ZCard = react_component_lib_1.createReactComponent('z-card');
exports.ZCardAlert = react_component_lib_1.createReactComponent('z-card-alert');
exports.ZCardBody = react_component_lib_1.createReactComponent('z-card-body');
exports.ZCardCover = react_component_lib_1.createReactComponent('z-card-cover');
exports.ZCardFooter = react_component_lib_1.createReactComponent('z-card-footer');
exports.ZCardHeader = react_component_lib_1.createReactComponent('z-card-header');
exports.ZCardIcon = react_component_lib_1.createReactComponent('z-card-icon');
exports.ZCardList = react_component_lib_1.createReactComponent('z-card-list');
exports.ZChip = react_component_lib_1.createReactComponent('z-chip');
exports.ZCombobox = react_component_lib_1.createReactComponent('z-combobox');
exports.ZCookiebar = react_component_lib_1.createReactComponent('z-cookiebar');
exports.ZDivider = react_component_lib_1.createReactComponent('z-divider');
exports.ZFooter = react_component_lib_1.createReactComponent('z-footer');
exports.ZFooterLink = react_component_lib_1.createReactComponent('z-footer-link');
exports.ZFooterSection = react_component_lib_1.createReactComponent('z-footer-section');
exports.ZFooterSocial = react_component_lib_1.createReactComponent('z-footer-social');
exports.ZHeader = react_component_lib_1.createReactComponent('z-header');
exports.ZHeading = react_component_lib_1.createReactComponent('z-heading');
exports.ZIcon = react_component_lib_1.createReactComponent('z-icon');
exports.ZIconPackage = react_component_lib_1.createReactComponent('z-icon-package');
exports.ZInfoBox = react_component_lib_1.createReactComponent('z-info-box');
exports.ZInput = react_component_lib_1.createReactComponent('z-input');
exports.ZInputLabel = react_component_lib_1.createReactComponent('z-input-label');
exports.ZInputMessage = react_component_lib_1.createReactComponent('z-input-message');
exports.ZLink = react_component_lib_1.createReactComponent('z-link');
exports.ZList = react_component_lib_1.createReactComponent('z-list');
exports.ZListItem = react_component_lib_1.createReactComponent('z-list-item');
exports.ZLogo = react_component_lib_1.createReactComponent('z-logo');
exports.ZMenu = react_component_lib_1.createReactComponent('z-menu');
exports.ZMenuDropdown = react_component_lib_1.createReactComponent('z-menu-dropdown');
exports.ZMenuSection = react_component_lib_1.createReactComponent('z-menu-section');
exports.ZModal = react_component_lib_1.createReactComponent('z-modal');
exports.ZModalLogin = react_component_lib_1.createReactComponent('z-modal-login');
exports.ZNavigationTab = react_component_lib_1.createReactComponent('z-navigation-tab');
exports.ZNavigationTabs = react_component_lib_1.createReactComponent('z-navigation-tabs');
exports.ZPaginationBar = react_component_lib_1.createReactComponent('z-pagination-bar');
exports.ZPaginationPage = react_component_lib_1.createReactComponent('z-pagination-page');
exports.ZPanelElem = react_component_lib_1.createReactComponent('z-panel-elem');
exports.ZRegistroTable = react_component_lib_1.createReactComponent('z-registro-table');
exports.ZRegistroTableBody = react_component_lib_1.createReactComponent('z-registro-table-body');
exports.ZRegistroTableCell = react_component_lib_1.createReactComponent('z-registro-table-cell');
exports.ZRegistroTableFooter = react_component_lib_1.createReactComponent('z-registro-table-footer');
exports.ZRegistroTableHead = react_component_lib_1.createReactComponent('z-registro-table-head');
exports.ZRegistroTableHeader = react_component_lib_1.createReactComponent('z-registro-table-header');
exports.ZRegistroTableRow = react_component_lib_1.createReactComponent('z-registro-table-row');
exports.ZRegistroTableStickyFooter = react_component_lib_1.createReactComponent('z-registro-table-sticky-footer');
exports.ZSelect = react_component_lib_1.createReactComponent('z-select');
exports.ZStepper = react_component_lib_1.createReactComponent('z-stepper');
exports.ZStepperItem = react_component_lib_1.createReactComponent('z-stepper-item');
exports.ZToggleButton = react_component_lib_1.createReactComponent('z-toggle-button');
exports.ZTooltip = react_component_lib_1.createReactComponent('z-tooltip');
exports.ZTypography = react_component_lib_1.createReactComponent('z-typography');
exports.ZUserDropdown = react_component_lib_1.createReactComponent('z-user-dropdown');
//# sourceMappingURL=components.js.map