/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { SfAlertType, SfLicenseType } from "./beans/index";
import { SfButtonSize, SfButtonType, SfButtonVariant, SfControlSize, SfDictionaryData, SfIconPosition, SfInputStatus, SfPopoverPosition } from "./beans";
export { SfAlertType, SfLicenseType } from "./beans/index";
export { SfButtonSize, SfButtonType, SfButtonVariant, SfControlSize, SfDictionaryData, SfIconPosition, SfInputStatus, SfPopoverPosition } from "./beans";
export namespace Components {
    interface ZAlert {
        /**
          * alert variant type
         */
        "type": SfAlertType;
    }
    interface ZMyzCard {
        /**
          * graphic variant (optional)
         */
        "cardtype"?: SfLicenseType;
        /**
          * faded status
         */
        "faded": boolean;
        /**
          * highlighted status
          * @default false
         */
        "ishighlighted": boolean;
        /**
          * pressed status
          * @default false
         */
        "ispressed": boolean;
    }
    interface ZMyzCardBody {
    }
    interface ZMyzCardCover {
        /**
          * default error image source
         */
        "defaultimg": string;
        /**
          * faded status
         */
        "faded": boolean;
        /**
          * image source
         */
        "img": string;
        /**
          * cover alt title
         */
        "titolo": string;
    }
    interface ZMyzCardDictionary {
        /**
          * card cover
         */
        "cover": string;
        /**
          * card is disabled
          * @default false
         */
        "disabled": boolean;
        /**
          * flip button label
          * @default "INFO"
         */
        "flipbuttonlabel": string;
        /**
          * card is flipped
          * @default false
         */
        "flipped": boolean;
        /**
          * hide info button
          * @default false
         */
        "hideinfobtn": boolean;
        /**
          * card title
         */
        "name": string;
    }
    interface ZMyzCardFooterSections {
    }
    interface ZMyzCardHeader {
        /**
          * card graphic variant (optional)
         */
        "cardtype"?: SfLicenseType;
        /**
          * faded status
         */
        "faded": boolean;
        /**
          * volume title
         */
        "titolo": string;
    }
    interface ZMyzCardInfo {
        /**
          * dictionary info
         */
        "data": string | SfDictionaryData;
        /**
          * tabindex link attribute (optional)
          * @default 0
         */
        "htmltabindex"?: number;
    }
    interface ZOtp {
        /**
          * Input number
          * @default 6
         */
        "inputNum"?: number;
        /**
          * Input message
         */
        "message"?: string;
        /**
          * Input status
         */
        "status"?: SfInputStatus;
    }
    interface ZSfButton {
        /**
          * the button icon position. Defaults to `left`
          * @default SfIconPosition.LEFT
         */
        "SfIconPosition"?: SfIconPosition;
        /**
          * defines a string value that labels the internal interactive element. Used for accessibility.
          * @default undefined
         */
        "ariaLabel": string | undefined;
        /**
          * HTML button disabled attribute.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * HTML <a> href attribute. If it is set, it renders an HTML <a> tag.
         */
        "href"?: string;
        /**
          * Identifier, should be unique.
         */
        "htmlid"?: string;
        /**
          * defines role attribute, used for accessibility.
         */
        "htmlrole"?: string;
        /**
          * `z-sf-icon` name to use (optional).
         */
        "icon"?: string;
        /**
          * HTML button name attribute.
         */
        "name"?: string;
        /**
          * Use `htmlrole` instead.
          * @deprecated This prop has been deprecated in favor of `htmlrole` for better accessibility.
          * @default ""
         */
        "role": string;
        /**
          * Available sizes: `big`, `small` and `x-small`. Defaults to `big`.
          * @default SfControlSize.BIG
         */
        "size"?: SfButtonSize | SfControlSize;
        /**
          * HTML a target attribute.
         */
        "target"?: string;
        /**
          * HTML button type attribute.
          * @default SfButtonType.BUTTON
         */
        "type"?: SfButtonType;
        /**
          * Graphical variant: `primary`, `secondary`, `tertiary`. Defaults to `primary`.
          * @default SfButtonVariant.PRIMARY
         */
        "variant"?: SfButtonVariant;
    }
    /**
     * Component to render an SVG icon from the internal icon set, selected by `name`.
     * This component automatically recognizes icons that have an indicator (e.g. `bg-color`, `font-color`, etc.), that can be filled with a custom color via the `indicatorColor` prop.
     */
    interface ZSfIcon {
        /**
          * Name of the CSS color token to use for the icon fill color (e.g. `blue500`).
         */
        "fill"?: string;
        /**
          * Icon height (optional)
         */
        "height"?: number | string;
        /**
          * HTML `id` attribute (optional)
         */
        "iconid"?: string;
        /**
          * Color to use to fill the icon's color indicator, if it has one. Can be any valid value for the `fill` svg attribute. If the icon passed through the `name` prop doesn't have a color indicator, this prop has no effect.
         */
        "indicatorColor"?: string;
        /**
          * Icon name
         */
        "name": string;
        /**
          * Icon width (optional)
         */
        "width"?: number | string;
    }
    interface ZSfInputMessage {
        /**
          * input disabled status (optional)
         */
        "disabled"?: boolean;
        /**
          * the id of the message element (optional)
          * @default `id-${sfRandomId()}`
         */
        "htmlId"?: string;
        /**
          * the role to set when both the message and the status are populated (optional)
          * @default "alert"
         */
        "htmlRole": null | string;
        /**
          * input helper message
         */
        "message": string;
        /**
          * input status (optional)
         */
        "status"?: SfInputStatus;
    }
    /**
     * Popover component.
     * This component displays a popover bound to an element.
     * It supports various positions and can automatically adjust it based on available space, accounting for scrollable containers.
     * Notes:
     * - If positioning has an odd behavior, consider manually adjusting the size of the slotted elements (using `width`, `height`, `max-width`, `max-height`, etc...) when its content is "fluid" (like text), because it can interfere with the position calculation (for example a long text on one single line can be bigger than the available space, letting the algorithm think the popover doesn't fits).
     */
    interface ZSfPopover {
        /**
          * The selector or the element bound with the popover. If string css selector is provided make sure to use a valid selector.
         */
        "bindTo"?: string | HTMLElement;
        /**
          * Whether to center the popup on the main side (according to "position").
          * @default false
         */
        "center": boolean;
        /**
          * Whether the popover can be closed by clicking outside of it or pressing the escape key. Otherwise, it will be closed only programmatically (by setting `open` to `false`). Default: `true`.
          * @default true
         */
        "closable": boolean;
        /**
          * The initial open state of the popover. Internal changes of this prop are emitted through the `openChange` event. Make sure to listen to that event if you need the updated state of the popover from the outside, to avoid inconsistent values.
          * @default false
         */
        "open": boolean;
        /**
          * The preferred position to render the popover. The popover will automatically search another position if not enough space is available for the preferred position. If the preferred position is not available, it will try to find the best position starting from `TOP` and going clockwise.
          * @default SfPopoverPosition.TOP
         */
        "position"?: SfPopoverPosition;
        /**
          * Whether to show popover's arrow.
          * @default false
         */
        "showArrow": boolean;
    }
}
export interface ZMyzCardDictionaryCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLZMyzCardDictionaryElement;
}
export interface ZMyzCardInfoCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLZMyzCardInfoElement;
}
export interface ZOtpCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLZOtpElement;
}
export interface ZSfPopoverCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLZSfPopoverElement;
}
declare global {
    interface HTMLZAlertElement extends Components.ZAlert, HTMLStencilElement {
    }
    var HTMLZAlertElement: {
        prototype: HTMLZAlertElement;
        new (): HTMLZAlertElement;
    };
    interface HTMLZMyzCardElement extends Components.ZMyzCard, HTMLStencilElement {
    }
    var HTMLZMyzCardElement: {
        prototype: HTMLZMyzCardElement;
        new (): HTMLZMyzCardElement;
    };
    interface HTMLZMyzCardBodyElement extends Components.ZMyzCardBody, HTMLStencilElement {
    }
    var HTMLZMyzCardBodyElement: {
        prototype: HTMLZMyzCardBodyElement;
        new (): HTMLZMyzCardBodyElement;
    };
    interface HTMLZMyzCardCoverElement extends Components.ZMyzCardCover, HTMLStencilElement {
    }
    var HTMLZMyzCardCoverElement: {
        prototype: HTMLZMyzCardCoverElement;
        new (): HTMLZMyzCardCoverElement;
    };
    interface HTMLZMyzCardDictionaryElementEventMap {
        "cardFlipped": any;
    }
    interface HTMLZMyzCardDictionaryElement extends Components.ZMyzCardDictionary, HTMLStencilElement {
        addEventListener<K extends keyof HTMLZMyzCardDictionaryElementEventMap>(type: K, listener: (this: HTMLZMyzCardDictionaryElement, ev: ZMyzCardDictionaryCustomEvent<HTMLZMyzCardDictionaryElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLZMyzCardDictionaryElementEventMap>(type: K, listener: (this: HTMLZMyzCardDictionaryElement, ev: ZMyzCardDictionaryCustomEvent<HTMLZMyzCardDictionaryElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLZMyzCardDictionaryElement: {
        prototype: HTMLZMyzCardDictionaryElement;
        new (): HTMLZMyzCardDictionaryElement;
    };
    interface HTMLZMyzCardFooterSectionsElement extends Components.ZMyzCardFooterSections, HTMLStencilElement {
    }
    var HTMLZMyzCardFooterSectionsElement: {
        prototype: HTMLZMyzCardFooterSectionsElement;
        new (): HTMLZMyzCardFooterSectionsElement;
    };
    interface HTMLZMyzCardHeaderElement extends Components.ZMyzCardHeader, HTMLStencilElement {
    }
    var HTMLZMyzCardHeaderElement: {
        prototype: HTMLZMyzCardHeaderElement;
        new (): HTMLZMyzCardHeaderElement;
    };
    interface HTMLZMyzCardInfoElementEventMap {
        "flipCard": any;
    }
    interface HTMLZMyzCardInfoElement extends Components.ZMyzCardInfo, HTMLStencilElement {
        addEventListener<K extends keyof HTMLZMyzCardInfoElementEventMap>(type: K, listener: (this: HTMLZMyzCardInfoElement, ev: ZMyzCardInfoCustomEvent<HTMLZMyzCardInfoElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLZMyzCardInfoElementEventMap>(type: K, listener: (this: HTMLZMyzCardInfoElement, ev: ZMyzCardInfoCustomEvent<HTMLZMyzCardInfoElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLZMyzCardInfoElement: {
        prototype: HTMLZMyzCardInfoElement;
        new (): HTMLZMyzCardInfoElement;
    };
    interface HTMLZOtpElementEventMap {
        "otpChange": any;
    }
    interface HTMLZOtpElement extends Components.ZOtp, HTMLStencilElement {
        addEventListener<K extends keyof HTMLZOtpElementEventMap>(type: K, listener: (this: HTMLZOtpElement, ev: ZOtpCustomEvent<HTMLZOtpElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLZOtpElementEventMap>(type: K, listener: (this: HTMLZOtpElement, ev: ZOtpCustomEvent<HTMLZOtpElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLZOtpElement: {
        prototype: HTMLZOtpElement;
        new (): HTMLZOtpElement;
    };
    interface HTMLZSfButtonElement extends Components.ZSfButton, HTMLStencilElement {
    }
    var HTMLZSfButtonElement: {
        prototype: HTMLZSfButtonElement;
        new (): HTMLZSfButtonElement;
    };
    /**
     * Component to render an SVG icon from the internal icon set, selected by `name`.
     * This component automatically recognizes icons that have an indicator (e.g. `bg-color`, `font-color`, etc.), that can be filled with a custom color via the `indicatorColor` prop.
     */
    interface HTMLZSfIconElement extends Components.ZSfIcon, HTMLStencilElement {
    }
    var HTMLZSfIconElement: {
        prototype: HTMLZSfIconElement;
        new (): HTMLZSfIconElement;
    };
    interface HTMLZSfInputMessageElement extends Components.ZSfInputMessage, HTMLStencilElement {
    }
    var HTMLZSfInputMessageElement: {
        prototype: HTMLZSfInputMessageElement;
        new (): HTMLZSfInputMessageElement;
    };
    interface HTMLZSfPopoverElementEventMap {
        "positionChange": {position: SfPopoverPosition};
        "openChange": {open: boolean};
    }
    /**
     * Popover component.
     * This component displays a popover bound to an element.
     * It supports various positions and can automatically adjust it based on available space, accounting for scrollable containers.
     * Notes:
     * - If positioning has an odd behavior, consider manually adjusting the size of the slotted elements (using `width`, `height`, `max-width`, `max-height`, etc...) when its content is "fluid" (like text), because it can interfere with the position calculation (for example a long text on one single line can be bigger than the available space, letting the algorithm think the popover doesn't fits).
     */
    interface HTMLZSfPopoverElement extends Components.ZSfPopover, HTMLStencilElement {
        addEventListener<K extends keyof HTMLZSfPopoverElementEventMap>(type: K, listener: (this: HTMLZSfPopoverElement, ev: ZSfPopoverCustomEvent<HTMLZSfPopoverElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLZSfPopoverElementEventMap>(type: K, listener: (this: HTMLZSfPopoverElement, ev: ZSfPopoverCustomEvent<HTMLZSfPopoverElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLZSfPopoverElement: {
        prototype: HTMLZSfPopoverElement;
        new (): HTMLZSfPopoverElement;
    };
    interface HTMLElementTagNameMap {
        "z-alert": HTMLZAlertElement;
        "z-myz-card": HTMLZMyzCardElement;
        "z-myz-card-body": HTMLZMyzCardBodyElement;
        "z-myz-card-cover": HTMLZMyzCardCoverElement;
        "z-myz-card-dictionary": HTMLZMyzCardDictionaryElement;
        "z-myz-card-footer-sections": HTMLZMyzCardFooterSectionsElement;
        "z-myz-card-header": HTMLZMyzCardHeaderElement;
        "z-myz-card-info": HTMLZMyzCardInfoElement;
        "z-otp": HTMLZOtpElement;
        "z-sf-button": HTMLZSfButtonElement;
        "z-sf-icon": HTMLZSfIconElement;
        "z-sf-input-message": HTMLZSfInputMessageElement;
        "z-sf-popover": HTMLZSfPopoverElement;
    }
}
declare namespace LocalJSX {
    interface ZAlert {
        /**
          * alert variant type
         */
        "type"?: SfAlertType;
    }
    interface ZMyzCard {
        /**
          * graphic variant (optional)
         */
        "cardtype"?: SfLicenseType;
        /**
          * faded status
         */
        "faded"?: boolean;
        /**
          * highlighted status
          * @default false
         */
        "ishighlighted"?: boolean;
        /**
          * pressed status
          * @default false
         */
        "ispressed"?: boolean;
    }
    interface ZMyzCardBody {
    }
    interface ZMyzCardCover {
        /**
          * default error image source
         */
        "defaultimg"?: string;
        /**
          * faded status
         */
        "faded"?: boolean;
        /**
          * image source
         */
        "img"?: string;
        /**
          * cover alt title
         */
        "titolo"?: string;
    }
    interface ZMyzCardDictionary {
        /**
          * card cover
         */
        "cover"?: string;
        /**
          * card is disabled
          * @default false
         */
        "disabled"?: boolean;
        /**
          * flip button label
          * @default "INFO"
         */
        "flipbuttonlabel"?: string;
        /**
          * card is flipped
          * @default false
         */
        "flipped"?: boolean;
        /**
          * hide info button
          * @default false
         */
        "hideinfobtn"?: boolean;
        /**
          * card title
         */
        "name"?: string;
        /**
          * when card is flipped
         */
        "onCardFlipped"?: (event: ZMyzCardDictionaryCustomEvent<any>) => void;
    }
    interface ZMyzCardFooterSections {
    }
    interface ZMyzCardHeader {
        /**
          * card graphic variant (optional)
         */
        "cardtype"?: SfLicenseType;
        /**
          * faded status
         */
        "faded"?: boolean;
        /**
          * volume title
         */
        "titolo"?: string;
    }
    interface ZMyzCardInfo {
        /**
          * dictionary info
         */
        "data"?: string | SfDictionaryData;
        /**
          * tabindex link attribute (optional)
          * @default 0
         */
        "htmltabindex"?: number;
        /**
          * flip card to front
         */
        "onFlipCard"?: (event: ZMyzCardInfoCustomEvent<any>) => void;
    }
    interface ZOtp {
        /**
          * Input number
          * @default 6
         */
        "inputNum"?: number;
        /**
          * Input message
         */
        "message"?: string;
        /**
          * Otp change event
         */
        "onOtpChange"?: (event: ZOtpCustomEvent<any>) => void;
        /**
          * Input status
         */
        "status"?: SfInputStatus;
    }
    interface ZSfButton {
        /**
          * the button icon position. Defaults to `left`
          * @default SfIconPosition.LEFT
         */
        "SfIconPosition"?: SfIconPosition;
        /**
          * defines a string value that labels the internal interactive element. Used for accessibility.
          * @default undefined
         */
        "ariaLabel"?: string | undefined;
        /**
          * HTML button disabled attribute.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * HTML <a> href attribute. If it is set, it renders an HTML <a> tag.
         */
        "href"?: string;
        /**
          * Identifier, should be unique.
         */
        "htmlid"?: string;
        /**
          * defines role attribute, used for accessibility.
         */
        "htmlrole"?: string;
        /**
          * `z-sf-icon` name to use (optional).
         */
        "icon"?: string;
        /**
          * HTML button name attribute.
         */
        "name"?: string;
        /**
          * Use `htmlrole` instead.
          * @deprecated This prop has been deprecated in favor of `htmlrole` for better accessibility.
          * @default ""
         */
        "role"?: string;
        /**
          * Available sizes: `big`, `small` and `x-small`. Defaults to `big`.
          * @default SfControlSize.BIG
         */
        "size"?: SfButtonSize | SfControlSize;
        /**
          * HTML a target attribute.
         */
        "target"?: string;
        /**
          * HTML button type attribute.
          * @default SfButtonType.BUTTON
         */
        "type"?: SfButtonType;
        /**
          * Graphical variant: `primary`, `secondary`, `tertiary`. Defaults to `primary`.
          * @default SfButtonVariant.PRIMARY
         */
        "variant"?: SfButtonVariant;
    }
    /**
     * Component to render an SVG icon from the internal icon set, selected by `name`.
     * This component automatically recognizes icons that have an indicator (e.g. `bg-color`, `font-color`, etc.), that can be filled with a custom color via the `indicatorColor` prop.
     */
    interface ZSfIcon {
        /**
          * Name of the CSS color token to use for the icon fill color (e.g. `blue500`).
         */
        "fill"?: string;
        /**
          * Icon height (optional)
         */
        "height"?: number | string;
        /**
          * HTML `id` attribute (optional)
         */
        "iconid"?: string;
        /**
          * Color to use to fill the icon's color indicator, if it has one. Can be any valid value for the `fill` svg attribute. If the icon passed through the `name` prop doesn't have a color indicator, this prop has no effect.
         */
        "indicatorColor"?: string;
        /**
          * Icon name
         */
        "name"?: string;
        /**
          * Icon width (optional)
         */
        "width"?: number | string;
    }
    interface ZSfInputMessage {
        /**
          * input disabled status (optional)
         */
        "disabled"?: boolean;
        /**
          * the id of the message element (optional)
          * @default `id-${sfRandomId()}`
         */
        "htmlId"?: string;
        /**
          * the role to set when both the message and the status are populated (optional)
          * @default "alert"
         */
        "htmlRole"?: null | string;
        /**
          * input helper message
         */
        "message"?: string;
        /**
          * input status (optional)
         */
        "status"?: SfInputStatus;
    }
    /**
     * Popover component.
     * This component displays a popover bound to an element.
     * It supports various positions and can automatically adjust it based on available space, accounting for scrollable containers.
     * Notes:
     * - If positioning has an odd behavior, consider manually adjusting the size of the slotted elements (using `width`, `height`, `max-width`, `max-height`, etc...) when its content is "fluid" (like text), because it can interfere with the position calculation (for example a long text on one single line can be bigger than the available space, letting the algorithm think the popover doesn't fits).
     */
    interface ZSfPopover {
        /**
          * The selector or the element bound with the popover. If string css selector is provided make sure to use a valid selector.
         */
        "bindTo"?: string | HTMLElement;
        /**
          * Whether to center the popup on the main side (according to "position").
          * @default false
         */
        "center"?: boolean;
        /**
          * Whether the popover can be closed by clicking outside of it or pressing the escape key. Otherwise, it will be closed only programmatically (by setting `open` to `false`). Default: `true`.
          * @default true
         */
        "closable"?: boolean;
        /**
          * Event emitted when the open state of the popover changes (e.g. when the user clicks outside the popover to close it, if `closable` is true).
         */
        "onOpenChange"?: (event: ZSfPopoverCustomEvent<{open: boolean}>) => void;
        /**
          * Fired when the position changes.
         */
        "onPositionChange"?: (event: ZSfPopoverCustomEvent<{position: SfPopoverPosition}>) => void;
        /**
          * The initial open state of the popover. Internal changes of this prop are emitted through the `openChange` event. Make sure to listen to that event if you need the updated state of the popover from the outside, to avoid inconsistent values.
          * @default false
         */
        "open"?: boolean;
        /**
          * The preferred position to render the popover. The popover will automatically search another position if not enough space is available for the preferred position. If the preferred position is not available, it will try to find the best position starting from `TOP` and going clockwise.
          * @default SfPopoverPosition.TOP
         */
        "position"?: SfPopoverPosition;
        /**
          * Whether to show popover's arrow.
          * @default false
         */
        "showArrow"?: boolean;
    }

    interface ZAlertAttributes {
        "type": SfAlertType;
    }
    interface ZMyzCardAttributes {
        "faded": boolean;
        "cardtype": SfLicenseType;
        "ispressed": boolean;
        "ishighlighted": boolean;
    }
    interface ZMyzCardCoverAttributes {
        "img": string;
        "titolo": string;
        "faded": boolean;
        "defaultimg": string;
    }
    interface ZMyzCardDictionaryAttributes {
        "name": string;
        "cover": string;
        "disabled": boolean;
        "flipped": boolean;
        "flipbuttonlabel": string;
        "hideinfobtn": boolean;
    }
    interface ZMyzCardHeaderAttributes {
        "titolo": string;
        "faded": boolean;
        "cardtype": SfLicenseType;
    }
    interface ZMyzCardInfoAttributes {
        "data": string | SfDictionaryData;
        "htmltabindex": number;
    }
    interface ZOtpAttributes {
        "inputNum": number;
        "status": SfInputStatus;
        "message": string;
    }
    interface ZSfButtonAttributes {
        "ariaLabel": string | undefined;
        "role": string;
        "htmlrole": string;
        "href": string;
        "target": string;
        "htmlid": string;
        "name": string;
        "disabled": boolean;
        "type": SfButtonType;
        "variant": SfButtonVariant;
        "icon": string;
        "SfIconPosition": SfIconPosition;
        "size": SfButtonSize | SfControlSize;
    }
    interface ZSfIconAttributes {
        "name": string;
        "height": string;
        "width": string;
        "iconid": string;
        "fill": string;
        "indicatorColor": string;
    }
    interface ZSfInputMessageAttributes {
        "message": string;
        "htmlId": string;
        "htmlRole": null | string;
        "status": SfInputStatus;
        "disabled": boolean;
    }
    interface ZSfPopoverAttributes {
        "position": SfPopoverPosition;
        "open": boolean;
        "bindTo": string | HTMLElement;
        "showArrow": boolean;
        "center": boolean;
        "closable": boolean;
    }

    interface IntrinsicElements {
        "z-alert": Omit<ZAlert, keyof ZAlertAttributes> & { [K in keyof ZAlert & keyof ZAlertAttributes]?: ZAlert[K] } & { [K in keyof ZAlert & keyof ZAlertAttributes as `attr:${K}`]?: ZAlertAttributes[K] } & { [K in keyof ZAlert & keyof ZAlertAttributes as `prop:${K}`]?: ZAlert[K] };
        "z-myz-card": Omit<ZMyzCard, keyof ZMyzCardAttributes> & { [K in keyof ZMyzCard & keyof ZMyzCardAttributes]?: ZMyzCard[K] } & { [K in keyof ZMyzCard & keyof ZMyzCardAttributes as `attr:${K}`]?: ZMyzCardAttributes[K] } & { [K in keyof ZMyzCard & keyof ZMyzCardAttributes as `prop:${K}`]?: ZMyzCard[K] };
        "z-myz-card-body": ZMyzCardBody;
        "z-myz-card-cover": Omit<ZMyzCardCover, keyof ZMyzCardCoverAttributes> & { [K in keyof ZMyzCardCover & keyof ZMyzCardCoverAttributes]?: ZMyzCardCover[K] } & { [K in keyof ZMyzCardCover & keyof ZMyzCardCoverAttributes as `attr:${K}`]?: ZMyzCardCoverAttributes[K] } & { [K in keyof ZMyzCardCover & keyof ZMyzCardCoverAttributes as `prop:${K}`]?: ZMyzCardCover[K] };
        "z-myz-card-dictionary": Omit<ZMyzCardDictionary, keyof ZMyzCardDictionaryAttributes> & { [K in keyof ZMyzCardDictionary & keyof ZMyzCardDictionaryAttributes]?: ZMyzCardDictionary[K] } & { [K in keyof ZMyzCardDictionary & keyof ZMyzCardDictionaryAttributes as `attr:${K}`]?: ZMyzCardDictionaryAttributes[K] } & { [K in keyof ZMyzCardDictionary & keyof ZMyzCardDictionaryAttributes as `prop:${K}`]?: ZMyzCardDictionary[K] };
        "z-myz-card-footer-sections": ZMyzCardFooterSections;
        "z-myz-card-header": Omit<ZMyzCardHeader, keyof ZMyzCardHeaderAttributes> & { [K in keyof ZMyzCardHeader & keyof ZMyzCardHeaderAttributes]?: ZMyzCardHeader[K] } & { [K in keyof ZMyzCardHeader & keyof ZMyzCardHeaderAttributes as `attr:${K}`]?: ZMyzCardHeaderAttributes[K] } & { [K in keyof ZMyzCardHeader & keyof ZMyzCardHeaderAttributes as `prop:${K}`]?: ZMyzCardHeader[K] };
        "z-myz-card-info": Omit<ZMyzCardInfo, keyof ZMyzCardInfoAttributes> & { [K in keyof ZMyzCardInfo & keyof ZMyzCardInfoAttributes]?: ZMyzCardInfo[K] } & { [K in keyof ZMyzCardInfo & keyof ZMyzCardInfoAttributes as `attr:${K}`]?: ZMyzCardInfoAttributes[K] } & { [K in keyof ZMyzCardInfo & keyof ZMyzCardInfoAttributes as `prop:${K}`]?: ZMyzCardInfo[K] };
        "z-otp": Omit<ZOtp, keyof ZOtpAttributes> & { [K in keyof ZOtp & keyof ZOtpAttributes]?: ZOtp[K] } & { [K in keyof ZOtp & keyof ZOtpAttributes as `attr:${K}`]?: ZOtpAttributes[K] } & { [K in keyof ZOtp & keyof ZOtpAttributes as `prop:${K}`]?: ZOtp[K] };
        "z-sf-button": Omit<ZSfButton, keyof ZSfButtonAttributes> & { [K in keyof ZSfButton & keyof ZSfButtonAttributes]?: ZSfButton[K] } & { [K in keyof ZSfButton & keyof ZSfButtonAttributes as `attr:${K}`]?: ZSfButtonAttributes[K] } & { [K in keyof ZSfButton & keyof ZSfButtonAttributes as `prop:${K}`]?: ZSfButton[K] };
        "z-sf-icon": Omit<ZSfIcon, keyof ZSfIconAttributes> & { [K in keyof ZSfIcon & keyof ZSfIconAttributes]?: ZSfIcon[K] } & { [K in keyof ZSfIcon & keyof ZSfIconAttributes as `attr:${K}`]?: ZSfIconAttributes[K] } & { [K in keyof ZSfIcon & keyof ZSfIconAttributes as `prop:${K}`]?: ZSfIcon[K] };
        "z-sf-input-message": Omit<ZSfInputMessage, keyof ZSfInputMessageAttributes> & { [K in keyof ZSfInputMessage & keyof ZSfInputMessageAttributes]?: ZSfInputMessage[K] } & { [K in keyof ZSfInputMessage & keyof ZSfInputMessageAttributes as `attr:${K}`]?: ZSfInputMessageAttributes[K] } & { [K in keyof ZSfInputMessage & keyof ZSfInputMessageAttributes as `prop:${K}`]?: ZSfInputMessage[K] };
        "z-sf-popover": Omit<ZSfPopover, keyof ZSfPopoverAttributes> & { [K in keyof ZSfPopover & keyof ZSfPopoverAttributes]?: ZSfPopover[K] } & { [K in keyof ZSfPopover & keyof ZSfPopoverAttributes as `attr:${K}`]?: ZSfPopoverAttributes[K] } & { [K in keyof ZSfPopover & keyof ZSfPopoverAttributes as `prop:${K}`]?: ZSfPopover[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "z-alert": LocalJSX.IntrinsicElements["z-alert"] & JSXBase.HTMLAttributes<HTMLZAlertElement>;
            "z-myz-card": LocalJSX.IntrinsicElements["z-myz-card"] & JSXBase.HTMLAttributes<HTMLZMyzCardElement>;
            "z-myz-card-body": LocalJSX.IntrinsicElements["z-myz-card-body"] & JSXBase.HTMLAttributes<HTMLZMyzCardBodyElement>;
            "z-myz-card-cover": LocalJSX.IntrinsicElements["z-myz-card-cover"] & JSXBase.HTMLAttributes<HTMLZMyzCardCoverElement>;
            "z-myz-card-dictionary": LocalJSX.IntrinsicElements["z-myz-card-dictionary"] & JSXBase.HTMLAttributes<HTMLZMyzCardDictionaryElement>;
            "z-myz-card-footer-sections": LocalJSX.IntrinsicElements["z-myz-card-footer-sections"] & JSXBase.HTMLAttributes<HTMLZMyzCardFooterSectionsElement>;
            "z-myz-card-header": LocalJSX.IntrinsicElements["z-myz-card-header"] & JSXBase.HTMLAttributes<HTMLZMyzCardHeaderElement>;
            "z-myz-card-info": LocalJSX.IntrinsicElements["z-myz-card-info"] & JSXBase.HTMLAttributes<HTMLZMyzCardInfoElement>;
            "z-otp": LocalJSX.IntrinsicElements["z-otp"] & JSXBase.HTMLAttributes<HTMLZOtpElement>;
            "z-sf-button": LocalJSX.IntrinsicElements["z-sf-button"] & JSXBase.HTMLAttributes<HTMLZSfButtonElement>;
            /**
             * Component to render an SVG icon from the internal icon set, selected by `name`.
             * This component automatically recognizes icons that have an indicator (e.g. `bg-color`, `font-color`, etc.), that can be filled with a custom color via the `indicatorColor` prop.
             */
            "z-sf-icon": LocalJSX.IntrinsicElements["z-sf-icon"] & JSXBase.HTMLAttributes<HTMLZSfIconElement>;
            "z-sf-input-message": LocalJSX.IntrinsicElements["z-sf-input-message"] & JSXBase.HTMLAttributes<HTMLZSfInputMessageElement>;
            /**
             * Popover component.
             * This component displays a popover bound to an element.
             * It supports various positions and can automatically adjust it based on available space, accounting for scrollable containers.
             * Notes:
             * - If positioning has an odd behavior, consider manually adjusting the size of the slotted elements (using `width`, `height`, `max-width`, `max-height`, etc...) when its content is "fluid" (like text), because it can interfere with the position calculation (for example a long text on one single line can be bigger than the available space, letting the algorithm think the popover doesn't fits).
             */
            "z-sf-popover": LocalJSX.IntrinsicElements["z-sf-popover"] & JSXBase.HTMLAttributes<HTMLZSfPopoverElement>;
        }
    }
}
