name: Continuous integration

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  prettier:
    name: Run prettier
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      PUPPETEER_SKIP_DOWNLOAD: true
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run prettier
        run: |
          ls -al .prettierignore .prettierrc.json
          yarn prettier --version
          yarn prettier --check .
  eslint:
    name: Run eslint
    runs-on: ubuntu-latest
    timeout-minutes: 20
    continue-on-error: true
    env:
      PUPPETEER_SKIP_DOWNLOAD: true
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run eslint
        run: yarn eslint src/
  stylelint:
    name: Stylelint
    runs-on: ubuntu-latest
    timeout-minutes: 20
    continue-on-error: true
    env:
      PUPPETEER_SKIP_DOWNLOAD: true
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run stylelint
        run: yarn stylelint 'src/**/*.css'
